services:
  - type: web
    name: singularity01
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
